language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install nltk
  - pip install pandas

# command to run tests
#script:
#  - pytest

notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: 